In [19]:
import os
import open3d as o3d
import copy
import numpy as np

In [107]:
obj_name = "072-a_toy_airplane"
input_obj = f"C:/Users/lucas/Desktop/UPC/MIT/tactile2object/ycb/0_in/{obj_name}.off"

out_dir = "0_in"

if not os.path.exists(out_dir):
    os.makedirs(out_dir)

In [108]:
mesh = o3d.io.read_triangle_mesh(input_obj)
mesh.compute_vertex_normals()
mesh.paint_uniform_color([0.7, 0.706, 0])
center = mesh.get_center()

In [109]:
num = lambda x : str(x).zfill(3)

for axis in np.identity(3, dtype=int):    
    for quadrant in range(4):
        ra, rb, rc = list((map(num, quadrant * axis * 90)))
        rotation = quadrant * axis * np.pi / 2

        mesh_r = copy.deepcopy(mesh)
        R = mesh.get_rotation_matrix_from_xyz(rotation)
        mesh_r.rotate(R, center=center)
        # o3d.visualization.draw_geometries([mesh, mesh_r])

        name = obj_name + "_" + ra + "_" + rb + "_" + rc + ".off"
        out_pth = os.path.join(out_dir, name)
        o3d.io.write_triangle_mesh(out_pth, mesh_r,
                                   write_vertex_normals=False, 
                                   write_triangle_uvs=False, 
                                   write_vertex_colors=False)


[Open3D WARNING] Write OFF cannot include triangle normals.
[Open3D WARNING] Write OFF cannot include triangle normals.
[Open3D WARNING] Write OFF cannot include triangle normals.
[Open3D WARNING] Write OFF cannot include triangle normals.
[Open3D WARNING] Write OFF cannot include triangle normals.
[Open3D WARNING] Write OFF cannot include triangle normals.
[Open3D WARNING] Write OFF cannot include triangle normals.
[Open3D WARNING] Write OFF cannot include triangle normals.
[Open3D WARNING] Write OFF cannot include triangle normals.
[Open3D WARNING] Write OFF cannot include triangle normals.
[Open3D WARNING] Write OFF cannot include triangle normals.
[Open3D WARNING] Write OFF cannot include triangle normals.


In [100]:
out_pth

'0_in\\072-a_toy_airplane_000_000_270.off'

In [56]:
R

array([[-1.0000000e+00, -1.2246468e-16,  0.0000000e+00],
       [ 1.2246468e-16, -1.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  1.0000000e+00]])

In [25]:
mesh = o3d.geometry.TriangleMesh.create_coordinate_frame()
mesh_r = copy.deepcopy(mesh)
R = mesh.get_rotation_matrix_from_xyz((np.pi / 2, 0, np.pi / 4))
mesh_r.rotate(R, center=center)
o3d.visualization.draw_geometries([mesh, mesh_r])

In [13]:
np.ndarray((10, 0, 0))

array([], shape=(10, 0, 0), dtype=float64)

In [21]:
input_obj = "1_scaled/003_cracker_box.off"

mesh = o3d.io.read_triangle_mesh(input_obj)
mesh.compute_vertex_normals()
mesh.paint_uniform_color([0.7, 0.706, 0])

R = mesh.get_rotation_matrix_from_xyz((np.pi / 2, 0, np.pi / 4))
mesh_r.rotate(R, center=(0, 0, 0))
o3d.visualization.draw_geometries([mesh, mesh_r])

In [27]:
input_obj = "2_watertight/003_cracker_box.off"

mesh = o3d.io.read_triangle_mesh(input_obj)
mesh.compute_vertex_normals()
mesh.paint_uniform_color([0.7, 0.706, 0])

R = mesh.get_rotation_matrix_from_xyz((np.pi / 2, 0, 0))
mesh_r.rotate(R, center=(0, 0, 0))
o3d.visualization.draw_geometries([mesh, mesh_r])

[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 


In [110]:
center

array([36.03013723, 30.86589313, 74.27965608])

In [16]:
mesh = o3d.geometry.TriangleMesh.create_coordinate_frame()
mesh_r = copy.deepcopy(mesh)
R = mesh.get_rotation_matrix_from_xyz((np.pi / 4, 0, 0))
mesh_r.rotate(R, center=(0, 0, 0))
o3d.visualization.draw_geometries([mesh, mesh_r])

array([0.05167549, 0.05167549, 0.05167549])